= Répéter les instantanés
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE Observability

== Vue d'ensemble

Cette page décrit les messages JSON exacts qui peuvent être envoyés pour le modèle de cohérence de la synchronisation de l'état de santé Repeat Snapshots.

== Propriété JSON : "health" (santé)

La santé peut être envoyée à l'API SUSE Observability Receiver à l'aide de la propriété `"health"` de l'xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[objet JSON commun.]

[tabs]
====
Exemple de santé `repeat_snapshots` JSON::
+
--
[,javascript]
----
{
   "apiKey":"<STACKSTATE_RECEIVER_API_KEY>",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "health":[
      {
        "consistency_model": "REPEAT_SNAPSHOTS",
        "start_snapshot": {
          "repeat_interval_s": 50
          //"expiry_interval_s": 200 Optional
        },
        "stop_snapshot": {},
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          }
        ]
      }
   ]
}
----
--
====

Chaque charge de données "Health Repeat Snapshots" contient les informations suivantes :

* *start_snapshot* - Optional. Le début d'un instantané doit être traité avant le traitement de `check_states`. Cela permet à SUSE Observability de comparer un instantané de flux avec celui reçu précédemment et de supprimer les états de contrôle qui ne sont plus présents dans l'instantané. Il contient les champs suivants en tant que métadonnées d'instantané :
 ** *repeat_interval_s* - Durée en secondes. Fréquence à laquelle la source externe enverra des données de santé à SUSE Observability. La valeur maximale autorisée est de 1800 (30 minutes).
 ** *expiry_interval_s* - Durée en secondes. Délai d'attente après la dernière mise à jour avant qu'un contrôle externe ne soit supprimé par SUSE Observability. Requis lors de l'utilisation de sous-flux.
* *stop_snapshot* - Facultatif. La fin d'un instantané sera traitée après le traitement de l'``optioncheck_states``.
* *stream* - Objet permettant d'identifier les instantanés et `check_states` qui appartiennent à un même ensemble. Il comprend les champs suivants :
 ** *urn* - ID de la source et du flux de données codé sous la forme d'un xref:/configure/topology/identifiers.adoc[URN] SUSE Observability correspondant à la convention suivante : `urn:health:<sourceId>:<streamId>` où `<sourceId>` est le nom de la source de données externe et `<streamId>` est un identifiant unique pour le flux de données de santé.
 ** *sub_stream_id* - Optional. Identifiant d'un sous-ensemble de données sur l'état de santé du flux. Lorsque les données de flux sont distribuées et communiquées par plusieurs agents, il est possible de réaliser des cycles de vie instantanés pour chaque agent. `sub_stream_id`
* *check_states* - Liste des états de contrôle. Chaque état de contrôle peut comporter les champs suivants :
 ** *checkStateId* - Identifiant de l'état de contrôle dans le système externe
 ** *message* - Facultatif. Message à afficher dans l'interface utilisateur de SUSE Observability. Les données seront interprétées comme du markdown permettant d'avoir des liens vers le contrôle du système externe qui a généré l'état du contrôle externe.
 ** *health* - L'une des valeurs suivantes de l'état de santé SUSE Observability Health : `Clear`, `Deviating`, `Critical`.
 ** *topologyElementIdentifier* - Utilisé pour lier l'état de contrôle à un élément topologique SUSE Observability.
 ** *name* - Nom de l'état de contrôle externe.

== Envoyer la santé à SUSE Observability

La santé peut être envoyée dans un message JSON via HTTP POST. Dans l'exemple ci-dessous, un instantané contenant deux états de contrôle est envoyé à SUSE Observability à partir d'un seul système de surveillance externe.

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "REPEAT_SNAPSHOTS",
      "start_snapshot": {
        "repeat_interval_s": 300
      },
      "stop_snapshot": {},
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        }
      ]
    }
  ]
}'
----
