= Éléments transactionnels
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE Observability

== Vue d'ensemble

Cette page décrit les messages JSON exacts qui peuvent être envoyés pour le modèle de cohérence Transactional Increments de la synchronisation de l'état de santé.

== Propriété JSON : "health" (santé)

La santé peut être envoyée à l'API SUSE Observability Receiver à l'aide de la propriété `"health"` de l'xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[objet JSON commun.]

[tabs]
====
Exemple de santé `transactional_increments` JSON::
+
--

[,javascript]
----
   "apiKey":"your api key",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "events":{},
   "metrics":[],
   "service_checks":[],
   "health":[
      {
        "consistency_model": "TRANSACTIONAL_INCREMENTS",
        "increment": {
              "checkpoint": {
                  "offset": 5,
                  "batch_index": 102
              },
              "previous_checkpoint": {
                  "offset": 5,
                  "batch_index": 100
              }
        },
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          },
          {
            "checkStateId": "checkStateId3",
            "delete": true
          }
        ]
      }
   ],
   "topologies":[]
----

--
====

Chaque charge utile de données sur les incréments transactionnels de santé contient les informations suivantes :

* *incrément* - Un objet d'incrément doit être présent dans chaque message. Cela permet à SUSE Observability de suivre la chaîne complète des messages et de détecter les retransmissions de données ou les lacunes inattendues dans les données. Il contient les champs suivants en tant que métadonnées d'incrémentation :
 ** *point de contrôle* - Objet fournissant le point de contrôle qui appartient à `check_states` présent dans le message, il comporte deux champs :
  *** *offset* - L'offset attribué aux messages par le pipeline de streaming. Par exemple, Kafka offset.
  *** *batch_index* - Optional. Lors de l'utilisation d'un seul message pour accumuler plusieurs `check_states`, l'index du lot représente le dernier index présent dans le message, ce qui permet d'envoyer des lots importants dans des appels d'API distincts.
 ** *previous_checkpoint* - Facultatif. Représente le point de contrôle précédemment communiqué, qui peut être vide lors de la toute première transmission du sous-flux. Cela permet à SUSE Observability de suivre l'évolution des données manquantes en amont.
* *stream* - Objet permettant d'identifier les instantanés et `check_states` qui appartiennent à un même ensemble. Il comprend les champs suivants :
 ** *urn* - ID de la source et du flux de données codé sous la forme d'un xref:/configure/topology/identifiers.adoc[URN] SUSE Observability correspondant à la convention suivante : `urn:health:<sourceId>:<streamId>` où `<sourceId>` est le nom de la source de données externe et `<streamId>` est un identifiant unique pour le flux de données de santé.
 ** *sub_stream_id* - Optional. Identifiant d'un sous-ensemble de données sur l'état de santé du flux. Lorsque les données de flux sont distribuées et communiquées par plusieurs agents, cela permet d'obtenir des cycles de vie instantanés pour chaque agent. `sub_stream_id`
* *check_states* - Liste des états de contrôle. Chaque état de contrôle peut comporter les champs suivants :
 ** *checkStateId* - Identifiant de l'état de contrôle dans le système externe
 ** *message* - Facultatif. Message à afficher dans l'interface utilisateur de SUSE Observability. Les données seront interprétées comme du markdown permettant d'avoir des liens vers le contrôle du système externe qui a généré l'état du contrôle externe.
 ** *health* - L'une des valeurs suivantes de l'état de santé SUSE Observability Health : `Clear`, `Deviating`, `Critical`.
 ** *topologyElementIdentifier* - Utilisé pour lier l'état de contrôle à un élément topologique SUSE Observability.
 ** *name* - Nom de l'état de contrôle externe.
 ** *delete* - Indicateur interprété comme une demande de suppression pour le site `checkStateId`. Même si les autres champs pour la création sont présents, par exemple, `name, health, ...` la suppression sera prioritaire.

== Envoyer la santé à SUSE Observability

La santé peut être envoyée dans un message JSON via HTTP POST. Dans l'exemple ci-dessous, un instantané contenant deux états de contrôle est envoyé à SUSE Observability à partir d'un seul système de surveillance externe.

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "TRANSACTIONAL_INCREMENTS",
      "increment": {
            "checkpoint": {
                "offset": 5,
                "batch_index": 102
            },
            "previous_checkpoint": {
                "offset": 5,
                "batch_index": 100
            }
      },
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        },
        {
          "checkStateId": "checkStateId3",
          "delete": true
        }
      ]
    }
  ]
}'
----
