= Secrets externes
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Secrets externes de SUSE Observability

== Vue d'ensemble

SUSE Observability peut prendre des secrets tels que la clé de licence, la clé d'api et les clés d'authentification par le biais de l'installation de helm, mais peut également prendre ces secrets à partir de secrets déjà provisionnés.

Voici comment configurer cette fonction.

== Obtenir la clé de licence à partir d'un secret externe

Créez un secret dans l'espace de noms dans lequel SUSE Observability est installé, de la forme suivante, en remplissant les blancs :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Obtenir le nom d'utilisateur et le mot de passe pour les notifications par courriel à partir d'un secret externe

Créez un secret dans l'espace de noms dans lequel SUSE Observability est installé, de la forme suivante, en remplissant les blancs :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== Obtenir la clé d'api à partir d'un secret externe

Créez un secret dans l'espace de noms dans lequel SUSE Observability est installé, de la forme suivante, en remplissant les blancs :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Obtenir des données d'authentification à partir d'un secret externe

Créez un secret dans l'espace de noms dans lequel SUSE Observability est installé, de la forme suivante.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

Selon la méthode d'authentification choisie, le champ `default_password` est remplacé par des données différentes. Voir les xref:/setup/security/authentication/authentication_options.adoc[options d'authentification] pour plus d'informations. Dans cet exemple, la configuration à xref:/setup/security/authentication/single_password.adoc[mot de passe unique] est utilisée.

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
