= Prise en charge du protocole ouvert de télémétrie de SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

SUSE Observability prend en charge deux versions du protocole OTLP, la version `grpc` (également appelée OTLP) et `http/protobuf` (également appelée OTLP sur HTTP). Dans la configuration du collecteur, vous pouvez choisir l'exportateur à utiliser, mais assurez-vous de configurer l'URL correcte pour SUSE Observability. La version `grpc` du protocole est préférable, car elle permet des charges utiles plus importantes et un débit plus élevé. Mais si votre infrastructure ne prend pas en charge `grpc`, vous pouvez passer à la version HTTP. Voir aussi le xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[dépannage]

== SUSE Cloud Observability

Les points de terminaison de SUSE Cloud Observability sont les suivants :

* OTLP : `otlp-<your-suse-observability>.app.stackstate.io:443` (sans le schéma URL)
* OTLP sur HTTP : `https://otlp-http-<your-suse-observability>.app.stackstate.io` (avec le schéma URL : `https`)

== SUSE Observability en auto-hébergement

Pour une installation auto-hébergée, vous devez activer l'un des points de terminaison, ou les deux, en configurant l'entrée pour SUSE Observability comme xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc#_configure_ingress_rule_for_open_telemetry[décrit ici.]

Lorsque SUSE Observability est exécuté dans le même cluster que le collecteur, vous pouvez également l'utiliser sans entrée en utilisant les points de terminaison du service, mais cela n'est possible qu'en utilisant le protocole HTTP :

* OTLP sur HTTP : `http://suse-observability-otel-collector.<namespace>.svc.cluster.local:4318`

Veillez à définir `insecure: true` dans la configuration du collecteur (voir la section suivante) pour permettre l'utilisation de points d'extrémité http ordinaires au lieu de https. 

Le protocole GRPC ne permet pas d'envoyer des informations d'identification par le biais d'une connexion non sécurisée, c'est pourquoi vous ne pouvez l'utiliser qu'en combinaison avec une configuration d'entrée sécurisée.

== Configuration du collecteur

=== Protocole OTLP

Les exemples de la configuration du collecteur utilisent le protocole OTLP comme suit :

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint, for example otlp-suse-observability.my.company.com:443
    endpoint: <otlp-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

=== OTLP Protocole HTTP

Pour utiliser le protocole OTLP over HTTP, utilisez plutôt l'exportateur `otlphttp`. Mettez également à jour toutes les références des exportateurs dans vos pipelines de `otlp/suse-observability` à `otlphttp/suse-observability`! Utilisez une recherche/remplacement pour vous assurer que vous modifiez toutes les occurrences.

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlphttp/stackstate:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp-http endpoint, for example https://otlp-http-suse-observability.my.company.com:443
    endpoint: <otlp-http-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable TLS entirely:
    #  insecure: true
    # To disalbe certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

Les possibilités de configuration sont plus nombreuses pour contrôler les exigences et le comportement exacts de l'exportateur. Par exemple, il est également possible d'utiliser un certificat racine CA personnalisé ou d'activer les certificats clients. Pour plus de détails, voir la https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md[documentation de l'exportateur OTLP sur le site].
