= Ouvrir Telemetry Collector en tant que proxy
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

La configuration normale du collecteur Opentelemetry pour l'échantillonnage des traces de queue est décrite xref:/setup/otel/collector.adoc[ici.]

La configuration ci-dessous décrit un déploiement qui ne fait que de la mise en lots, sans autre traitement des traces, des métriques ou des journaux.  Il s'agit d'un proxy de sécurité qui existe en dehors du cluster SUSE Observability, mais au sein d'une infrastructure réseau de confiance.  Les informations d'identification de sécurité pour le proxy et SUSE Observability peuvent être configurées séparément, ce qui ajoute une couche d'authentification qui ne réside pas dans l'appelant, mais dans l'hôte.

image::otel/aws_nodejs_otel_proxy_collector_configuration.svg[Instrumentation AWS Lambda avec Opentelemetry via un collecteur proxy]

.otel-collector.yaml
[,yaml]
----
mode: deployment
presets:
   kubernetesAttributes:
      enabled: true
      # You can also configure the preset to add all the associated pod's labels and annotations to you telemetry.
      # The label/annotation name will become the resource attribute's key.
      extractAllPodLabels: true
extraEnvsFrom:
   - secretRef:
        name: open-telemetry-collector
image:
   repository: "otel/opentelemetry-collector-k8s"

config:
   receivers:
      otlp:
         protocols:
            grpc:
               endpoint: 0.0.0.0:4317
            http:
               endpoint: 0.0.0.0:4318

   exporters:
      # Exporter for traces to traffic mirror (used by the common config)
      otlp:
         endpoint: <url for opentelemetry ingestion by suse observability>
         auth:
            authenticator: bearertokenauth

   extensions:
      bearertokenauth:
         scheme: SUSEObservability
         token: "${env:API_KEY}"

   service:
      extensions: [health_check, bearertokenauth]
      pipelines:
         traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    # "12.34.56.78/32" IP address of NatGateway in the VPC where the otel data is originating from
    #  nginx.ingress.kubernetes.io/whitelist-source-range: "12.34.56.78/32"
  hosts:
    - host: "otlp-collector-proxy.${CLUSTER_NAME}"
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 4317
  tls:
    - secretName: ${CLUSTER_NODOT}-ecc-tls
      hosts:
        - "otlp-collector-proxy.${CLUSTER_NAME}"
----


[discrete]
=== Liste blanche des sources d'entrée

Pour souligner le rôle du collecteur proxy en tant que mesure de sécurité, il est recommandé d'utiliser une liste blanche pour filtrer les données provenant de sources non fiables et/ou inconnues.  En revanche, le collecteur d'ingestion de SUSE Observability peut être amené à accepter des données provenant de plusieurs sources, et le maintien d'une liste blanche à ce niveau n'est pas très évolutif.
