= Documentation de SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}

Il s'agit de la dernière documentation de SUSE Observability. Sélectionnez les thèmes dans le menu de gauche.

Pour les versions plus anciennes de la documentation, utilisez l' https://archivedocs.stackstate.com[archive].

== Commencer

Si vous êtes un utilisateur de Rancher Prime, consultez lexref:/k8s-quick-start-guide.adoc[guide] xref:/k8s-suse-rancher-prime.adoc[de]xref:/k8s-quick-start-guide.adoc[démarrage] de Rancher Prime. Si vous êtes un utilisateur de SUSE Cloud Observability, consultez lexref:/suse-cloud-observability-quick-start-guide.adoc[guide de démarrage rapide]. Si vous utilisez SUSE Cloud Observability sur AWS, consultez lexref:/suse-cloud-observability-quick-start-guide.adoc[guide de démarrage rapide de SUSE Cloud Observability].

== Vous ne trouvez rien ?

Utilisez la barre de recherche en haut à droite. Si vous pensez qu'il manque de la documentation, faites-le nous savoir sur le site https://scc.suse.com/[SUSE Observability support site].

== Dépannage et assistance

Des questions ? Nous pouvons vous aider. Trouvez l'équipe de support sur lehttps://scc.suse.com/[site] SUSE.

== SUSE Observability en mode auto-hébergé

Utilisez SUSE Observability Self-hosted pour observer un vaste ensemble de technologies à partir de vos propres centres de données ou de l'informatique en nuage.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability en mode auto-hébergé]

== SUSE Cloud Observability

Utilisez SUSE Cloud Observability pour observer les technologies cloud, telles que Kubernetes et les services AWS.

xref:/suse-cloud-observability/user-management.adoc[SUSE Cloud Observability docs]
