= Instrumenter les applications Node.js
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Instrumentation automatique

L'instrumentation automatique pour Node.js se fait en incluant les bibliothèques Javascript d'instrumentation automatique dans votre application. Un large éventail de https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#_supported_instrumentations[bibliothèques et de cadres de travail]

L'instrumentation automatique ne nécessite aucune modification de l'application. Pour l'installer, suivez les étapes suivantes :

. Ajoutez le SDK d'instrumentation Open Telemetry à votre application :
+
[,bash]
----
npm install --save @opentelemetry/api
npm install --save @opentelemetry/auto-instrumentations-node
----

. Mettez à jour la commande qui démarre votre application pour charger le SDK, soit en mettant à jour le point d'entrée ou la commande de l'image docker, soit en mettant à jour le site `command` dans le manifeste Kubernetes de votre application. Ajouter `--require @opentelemetry/auto-instrumentations-node/register`:
+
[,bash]
----
node --require @opentelemetry/auto-instrumentations-node/register app.js
----

. Déployez votre application avec les variables d'environnement supplémentaires xref:/setup/otel/instrumentation/sdk-exporter-config.adoc[pour configurer le nom du service et le point de terminaison de l'exportateur]. Les protocoles pris en charge sont gRPC et protobuf sur HTTP.
. Vérifiez que SUSE Observability reçoit des traces et/ou des mesures en recherchant les mesures / traces dans l'explorateur de mesures / traces pour le nom de votre service.

Pour plus de détails, veuillez consulter la https://opentelemetry.io/docs/languages/js/automatic/[documentation de].

[CAUTION]
====
L'instrumentation automatique configurée via des variables d'environnement ne prend en charge que les traces jusqu'à ce que le https://github.com/open-telemetry/opentelemetry-js/issues/4551[problème de] soit résolu. Pour activer les mesures de l'instrumentation automatique, il est nécessaire de modifier le code. Veuillez suivre les instructions de la https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[documentation] pour effectuer ces changements.
====


== Instrumentation manuelle

L'instrumentation manuelle peut être utilisée lorsque vous avez besoin de mesures, de traces ou de journaux provenant de parties du code qui ne sont pas prises en charge par l'instrumentation automatique. Par exemple, les bibliothèques non prises en charge, le code interne ou les mesures au niveau de l'entreprise.

Pour capturer ces données, vous devez modifier votre application.

. Inclure le SDK Open Telemetry comme dépendance
. Ajoutez du code à votre application pour capturer des métriques, des intervalles ou des journaux lorsque cela est nécessaire.

Vous trouverez une documentation détaillée à ce sujet sur le site https://opentelemetry.io/docs/languages/js/instrumentation/[Open Telemetry Javascript SDK doc pages.]

Assurez-vous d'utiliser l'exportateur OTLP et de configurer correctement le point de terminaison de l'exportateur à partir du code. Voir également la https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[documentation de]. En supposant que vous ayez configuré l'exportateur comme xref:/setup/otel/collector.adoc[indiqué dans la documentation], le point de terminaison à configurer est `http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317`, à l'aide de gRPC. Voir aussi xref:/setup/otel/instrumentation/sdk-exporter-config.adoc#_grpc_vs_http[gRPC vs HTTP] au cas où gRPC poserait problème.
