= Configuration des exportateurs de SDK
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Pour envoyer des données à SUSE Observability, les SDK utilisés pour instrumenter votre application utilisent un exportateur intégré. Une configuration prête pour la production utilise <<_with_a_collector_production_setup,un collecteur>> proche de vos applications instrumentées pour envoyer les données à SUSE Observability, mais il est également possible de faire en sorte que l'application instrumentée <<_without_a_collector,envoie directement les>> données télémétriques à SUSE Observability.

== Avec un collecteur (installation de production)

=== Configuration de l'exportateur SDK pour Kubernetes

Tous les SDK, quelle que soit la langue, utilisent la même configuration de base pour définir le Open Telemetry https://opentelemetry.io/docs/concepts/glossary/#_service[nom du service] et le point final de l'exportateur (c'est-à-dire l'endroit où la télémétrie est envoyée).

Ceux-ci peuvent être configurés en définissant des variables d'environnement pour votre application instrumentée.

Dans Kubernetes, définissez ces variables d'environnement dans le manifeste de votre charge de travail (remplacez `<the-service-name>` par le nom de votre service d'application) :

[,yaml]
----
...
spec:
  containers:
  - env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317
    - name: OTEL_SERVICE_NAME
      value: <the-service-name>
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: grpc
...
----

Le point final spécifié dans l'exemple suppose que le collecteur a été installé en utilisant les valeurs par défaut du xref:/setup/otel/collector.adoc[guide d'installation]. Il utilise le port `4317` qui utilise la version `gRPC` du protocole OTLP. Certains instruments ne prennent en charge que le protocole HTTP ; dans ce cas, il convient d'utiliser le port `4318`.

Le nom du service peut également être dérivé des étiquettes Kubernetes qui peuvent déjà être présentes. Voici un exemple :

[,yaml]
----
spec:
  containers:
  - env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
----

=== Configuration du SDK Exporter pour d'autres installations

Pour configurer le SDK, définissez ces variables d'environnement pour votre application :

[,bash]
----
export OTEL_EXPORTER_OTLP_ENDPOINT="http://<the-host-for-the-collector>:4317"
export OTEL_EXPORTER_OTLP_PROTOCOL="grpc"
export OTEL_SERVICE_NAME="<the-service-name>"
export OTEL_RESOURCE_ATTRIBUTES='service.namespace=<the-namespace>'
----

L'exemple utilise le port `4317` qui utilise la version `gRPC` du protocole OTLP. Certains instruments ne prennent en charge que le protocole HTTP, qui utilise le port `4318` et dont le protocole est défini sur `http`. Utilisez la documentation SDK de votre langue pour vérifier quel protocole est pris en charge par le SDK. Les champs `OTEL_EXPORTER_OLTP_ENDPOINT` et `OTEL_EXPORTER_OTLP_PROTOCOL` peuvent être omis, ils ont des valeurs par défaut qui envoient les données au point de terminaison préféré sur l'hôte local.

L'adresse `OTEL_RESOURCE_ATTRIBUTES` est facultative et, outre la définition d'un espace de noms de services, elle peut être utilisée pour définir d'autres attributs de ressources dans une liste séparée par des virgules.

=== gRPC vs HTTP

OTLP, le protocole de télémétrie ouvert, prend en charge gRPC et protobuf sur HTTP. Dans la section précédente, le protocole de l'exportateur est fixé à `gRPC`, ce qui donne généralement les meilleures performances. Outre le fait que le SDK ne prend pas en charge gRPC, il peut y avoir d'autres raisons de préférer HTTP :

* Certains pare-feu ne sont pas configurés pour gérer gRPC
* Les proxys (inversés) et les équilibreurs de charge peuvent ne pas prendre en charge gRPC sans configuration supplémentaire.
* Les connexions de longue durée de gRPC peuvent poser des problèmes lors de l'équilibrage de la charge.

Pour passer à HTTP au lieu de gRPC, changez le protocole en `http` _et_ utilisez le port `4318`.

En résumé, vous pouvez essayer d'utiliser HTTP si gRPC ne vous convient pas :

* `grpc` Le protocole utilise le port `4317` sur le collecteur
* `http` Le protocole utilise le port `4318` sur le collecteur

== Sans collecteur

Dans les petites configurations de test, il peut être pratique d'envoyer directement les données de votre application instrumentée à SUSE Observability. La seule différence par rapport à la configuration du collecteur décrite ci-dessus est l'utilisation d'une valeur différente pour `OTEL_EXPORTER_OTLP_ENDPOINT`:

* Pour gRPC, utilisez le point de terminaison OTLP pour SUSE Observability, voir la xref:/setup/otel/otlp-apis.adoc[page des API OTLP].
* Pour HTTP, utilisez le point de terminaison OTLP over HTTP pour SUSE Observability, voir la xref:/setup/otel/otlp-apis.adoc[page API OTLP].

[NOTE]
====
Remplacez l'URL du collecteur *et le* port par les points d'extrémité de SUSE Observability. Selon votre installation de SUSE Observability, les ports seront différents.
====

