= Rôles
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Vue d'ensemble

Chaque utilisateur de SUSE Observability doit se voir attribuer un sujet et un ensemble de xref:/setup/security/rbac/rbac_permissions.adoc[permissions]; cette combinaison est appelée rôle. Un rôle décrit un groupe d'utilisateurs qui peuvent accéder à un ensemble de données spécifique. SUSE Observability est livré avec un ensemble de rôles prédéfinis et vous pouvez également créer des rôles en fonction de vos besoins.

== Rôles prédéfinis

Quatre rôles sont prédéfinis dans SUSE Observability :

* *Administrateur* - a un accès complet à toutes les vues et dispose de toutes les autorisations.
* *Power User* - généralement accordé à un utilisateur qui doit configurer SUSE Observability pour une ou plusieurs équipes, mais qui ne gérera pas l'ensemble de l'installation de SUSE Observability.
* *Kubernetes Troubleshooter* - dispose de toutes les autorisations nécessaires pour utiliser SUSE Observability à des fins de dépannage, y compris la possibilité d'activer/désactiver les moniteurs, de créer des vues personnalisées et d'utiliser le Cli.
* *Invité*: accès en lecture seule à SUSE Observability.

Les autorisations attribuées à chaque rôle SUSE Observability prédéfini sont indiquées ci-dessous. Pour plus de détails sur les différentes autorisations et sur la manière de les gérer à l'aide de l'interface CLI de `sts`, voir les xref:/setup/security/rbac/rbac_permissions.adoc[autorisations du contrôle d'accès basé sur les rôles (RBAC)].

[tabs]
====
Administrateur::
+
--

Le rôle d'administrateur (`stackstate-admin`) : toutes les autorisations sont attribuées.

Les autorisations attribuées au rôle prédéfini d'administrateur (`stackstate-admin`) sont énumérées ci-dessous. Elles ont été récupérées à l'aide de l'interface CLI de `sts`. Pour plus de détails sur les différentes autorisations et sur la manière de les gérer à l'aide de l'interface CLI de `sts`, voir les xref:/setup/security/rbac/rbac_permissions.adoc[autorisations RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-admin
PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-ingestion-api-keys       | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-service-tokens           | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-ingestion-api-keys       | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-service-tokens           | system
delete-stackpack-configurations | system
delete-sync-data                | system
delete-views                    | system
execute-component-actions       | system
execute-monitors                | system
execute-restricted-scripts      | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-ingestion-api-keys          | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-service-tokens              | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-permissions              | system
update-scoped-permissions       | system
update-settings                 | system
update-stackpack-configurations | system
update-stackpacks               | system
update-views                    | system
update-visualization            | system
----

--
Utilisateur expérimenté::
+
--

Le rôle d'utilisateur expérimenté (`stackstate-power-user`) dispose de toutes les autorisations de l'administrateur, à l'exception des autorisations suivantes :

* `execute-restricted-scripts`
* `update-permissions`
* `update-stackpacks`

Les autorisations attribuées au rôle prédéfini de Power User (`stackstate-power-user`) sont énumérées ci-dessous. Elles ont été récupérées à l'aide du CLI `sts`. Pour plus de détails sur les différentes autorisations et sur la manière de les gérer à l'aide de l'interface CLI de `sts`, voir les xref:/setup/security/rbac/rbac_permissions.adoc[autorisations RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-power-user
PERMISSION                      | RESOURCE
create-dashboards               | system
create-favorite-dashboards      | system
create-favorite-views           | system
create-metric-bindings          | system
create-monitors                 | system
create-notifications            | system
create-stackpack-configurations | system
create-views                    | system
delete-dashboards               | system
delete-favorite-dashboards      | system
delete-favorite-views           | system
delete-metric-bindings          | system
delete-monitors                 | system
delete-notifications            | system
delete-stackpack-configurations | system
delete-sync-data                | system
execute-component-actions       | system
execute-monitors                | system
execute-scripts                 | system
get-agents                      | system
get-api-tokens                  | system
get-dashboards                  | system
get-metric-bindings             | system
get-metrics                     | system
get-monitors                    | system
get-notifications               | system
get-permissions                 | system
get-settings                    | system
get-stackpacks                  | system
get-sync-data                   | system
get-system-notifications        | system
get-topic-messages              | system
get-topology                    | system
get-traces                      | system
get-views                       | system
update-dashboards               | system
update-metric-bindings          | system
update-metrics                  | system
update-monitors                 | system
update-notifications            | system
update-settings                 | system
update-stackpack-configurations | system
update-views                    | system
update-visualization            | system
----

--
Dépanneur::
+
--

Le rôle de dépanneur (`stackstate-k8s-troubleshooter`) a accès à toutes les données disponibles dans SUSE Observability et a la possibilité de créer des vues et d'activer/désactiver des moniteurs.

Les autorisations attribuées au rôle prédéfini de dépanneur sont énumérées ci-dessous. Elles ont été récupérées à l'aide de l'interface CLI de `sts`. Pour plus de détails sur les différentes autorisations et sur la manière de les gérer à l'aide de l'interface CLI de `sts`, voir les xref:/setup/security/rbac/rbac_permissions.adoc[autorisations RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-k8s-troubleshooter
PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
create-monitors            | system
create-notifications       | system
create-views               | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
delete-monitors            | system
delete-notifications       | system
delete-views               | system
execute-monitors           | system
get-agents                 | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-stackpacks             | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-monitors            | system
update-notifications       | system
update-stackpacks          | system
update-views               | system
update-visualization       | system
----

--
Invité::
+
--

Le rôle d'invité (`stackstate-guest`) a un accès en lecture seule à SUSE Observability.

Les autorisations attribuées au rôle prédéfini d'invité sont énumérées ci-dessous. Elles ont été récupérées à l'aide de l'interface CLI de `sts`. Pour plus de détails sur les différentes autorisations et sur la manière de les gérer à l'aide de l'interface CLI de `sts`, voir les xref:/setup/security/rbac/rbac_permissions.adoc[autorisations RBAC].

[,text]
----
❯ ./sts rbac describe-permissions --subject stackstate-guest
PERMISSION                 | RESOURCE
create-dashboards          | system
create-favorite-dashboards | system
create-favorite-views      | system
delete-dashboards          | system
delete-favorite-dashboards | system
delete-favorite-views      | system
get-api-tokens             | system
get-dashboards             | system
get-metric-bindings        | system
get-metrics                | system
get-monitors               | system
get-notifications          | system
get-permissions            | system
get-settings               | system
get-system-notifications   | system
get-topic-messages         | system
get-traces                 | system
get-views                  | system
update-dashboards          | system
update-visualization       | system
----

--
====

== Rôles personnalisés (Configuration RBAC)

En plus des rôles prédéfinis (`stackstate-admin`, `stackstate-power-user`, `stackstate-k8s-troubleshooter`, `stackstate-guest`), qui sont toujours disponibles, des rôles personnalisés peuvent être ajoutés. Il existe plusieurs façons d'ajouter des rôles personnalisés :

. via le fichier de configuration, avec les mêmes droits que les rôles prédéfinis
. via le fichier de configuration, avec des autorisations personnalisées
. en utilisant le CLI `sts`, les sujets et leurs permissions sont stockés dans la base de données et peuvent être modifiés pendant l'exécution.

Les rôles ajoutés via le fichier de configuration nécessitent un redémarrage et entraînent donc une courte période d'indisponibilité. Les rôles créés à l'aide de l'interface de programmation sont stockés dans la base de données et peuvent être modifiés au moment de l'exécution.

=== Noms personnalisés pour les rôles prédéfinis

Utilisez cette option lorsque les rôles prédéfinis de SUSE Observability conviennent bien, mais que le fournisseur d'authentification externe a des noms différents pour les rôles. Par exemple, lorsque le fournisseur d'authentification LDAP a des rôles similaires mais nommés différemment, incluez cet extrait YAML dans une page `authentication.yaml` pour donner aux rôles provenant de LDAP les mêmes permissions et portées que les rôles prédéfinis équivalents.

[,yaml]
----
stackstate:
  authentication:
    roles:
      guest: ["ldap-guest-role"]
      powerUser: ["ldap-power-user-role"]
      admin: ["ldap-admin-role"]
      k8sTroubleshooter: ["ldap-troubleshooter-role"]
----

Pour l'utiliser dans votre installation SUSE Observability (ou dans une instance déjà en cours d'exécution, notez que cela redémarrera l'API) :

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== Rôles personnalisés via le fichier de configuration

Pour configurer un nouveau rôle appelé `development-troubleshooter`, qui autorisera les mêmes permissions que le rôle prédéfini de dépanneur, mais uniquement pour le cluster `dev-test`, incluez cet extrait YAML dans un fichier `authentication.yaml`:

[,yaml]
----
stackstate:
  authentication:
    roles:
      custom:
        development-troubleshooter:
          systemPermissions:
          - create-dashboards
          - create-favorite-dashboards
          - create-favorite-views
          - create-monitors
          - create-notifications
          - create-views
          - delete-dashboards
          - delete-favorite-dashboards
          - delete-favorite-views
          - delete-monitors
          - delete-notifications
          - delete-views
          - execute-monitors
          - get-agents
          - get-api-tokens
          - get-dashboards
          - get-metric-bindings
          - get-metrics
          - get-monitors
          - get-notifications
          - get-permissions
          - get-settings
          - get-stackpacks
          - get-system-notifications
          - get-topic-messages
          - get-traces
          - get-views
          - update-dashboards
          - update-monitors
          - update-notifications
          - update-stackpacks
          - update-views
          - update-visualization
          resourcePermissions:
            get-topology:
            - "cluster-name:dev-test"
----

Pour l'utiliser dans votre installation SUSE Observability (ou dans une instance déjà en cours d'exécution, notez que cela redémarrera l'API) :

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
  --values authentication.yaml \
suse-observability \
suse-observability/suse-observability
----

=== Rôles personnalisés via le CLI (Observability RBAC)

Pour configurer un nouveau rôle appelé `development-troubleshooter`, qui permettra les mêmes autorisations que le rôle normal de dépanneur, mais uniquement pour le cluster `dev-test`, un nouveau sujet doit être créé. En outre, ce sujet doit se voir attribuer l'ensemble des autorisations requises :

. Créez le sujet (avec le même nom que le rôle, la correspondance rôle-sujet est basée sur le nom et sensible à la casse) :
+
[,text]
----
sts rbac create-subject --subject development-troubleshooter
sts rbac grant --subject development-troubleshooter --permission get-topology --resource "cluster-name:dev-test"'
----
+

. Les sujets configurés ont besoin de permissions pour accéder à certaines parties de l'interface utilisateur et pour y exécuter des actions. Pour accorder les mêmes autorisations que le rôle de dépanneur, suivez l'exemple ci-dessous :
+
[,text]
----
sts rbac grant --subject development-troubleshooter --permission create-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission create-favorite-views
sts rbac grant --subject development-troubleshooter --permission create-monitors
sts rbac grant --subject development-troubleshooter --permission create-notifications
sts rbac grant --subject development-troubleshooter --permission create-views
sts rbac grant --subject development-troubleshooter --permission delete-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-dashboards
sts rbac grant --subject development-troubleshooter --permission delete-favorite-views
sts rbac grant --subject development-troubleshooter --permission delete-monitors
sts rbac grant --subject development-troubleshooter --permission delete-notifications
sts rbac grant --subject development-troubleshooter --permission delete-views
sts rbac grant --subject development-troubleshooter --permission execute-monitors
sts rbac grant --subject development-troubleshooter --permission get-agents
sts rbac grant --subject development-troubleshooter --permission get-api-tokens
sts rbac grant --subject development-troubleshooter --permission get-dashboards
sts rbac grant --subject development-troubleshooter --permission get-metric-bindings
sts rbac grant --subject development-troubleshooter --permission get-metrics
sts rbac grant --subject development-troubleshooter --permission get-monitors
sts rbac grant --subject development-troubleshooter --permission get-notifications
sts rbac grant --subject development-troubleshooter --permission get-permissions
sts rbac grant --subject development-troubleshooter --permission get-settings
sts rbac grant --subject development-troubleshooter --permission get-stackpacks
sts rbac grant --subject development-troubleshooter --permission get-system-notifications
sts rbac grant --subject development-troubleshooter --permission get-topic-messages
sts rbac grant --subject development-troubleshooter --permission get-traces
sts rbac grant --subject development-troubleshooter --permission get-views
sts rbac grant --subject development-troubleshooter --permission update-dashboards
sts rbac grant --subject development-troubleshooter --permission update-monitors
sts rbac grant --subject development-troubleshooter --permission update-notifications
sts rbac grant --subject development-troubleshooter --permission update-stackpacks
sts rbac grant --subject development-troubleshooter --permission update-views
sts rbac grant --subject development-troubleshooter --permission update-visualization
----

Veuillez noter que le nom du sujet, ainsi que les autorisations, sont sensibles à la casse.
