= Dépannage des graphiques métriques personnalisés
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Vue d'ensemble

* <<_the_metric_chart_doesnt_show_on_the_highlights_page_of_a_component,Le graphique métrique ne s'affiche pas sur la page des faits marquants d'un composant>>
* <<_the_metric_chart_doesnt_show_on_the_metrics_perspective_of_a_component,Le tableau des métriques ne s'affiche pas dans la perspective des métriques d'un composant>>
* <<_the_metric_chart_on_a_component_remains_empty_no_data,Le graphique métrique d'un composant reste vide ("pas de données")>>

== Le graphique métrique ne s'affiche pas sur la page des faits marquants d'un composant

Pour l'instant, il n'est pas possible de personnaliser les graphiques métriques qui sont affichés sur la page des points forts des composants. Les graphiques des liaisons métriques personnalisées ne seront affichés que dans la perspective des métriques.

== Le tableau des métriques ne s'affiche pas dans la perspective des métriques d'un composant

La requête `scope` sur une liaison métrique est utilisée pour déterminer si un composant affiche la liaison métrique. Si un composant n'affiche pas de liaison métrique, vérifiez que la requête topologique dans l'étendue correspond au composant.

Vérifiez d'abord que le composant a bien les étiquettes et/ou le type de composant attendus sur la page de présentation du composant, le nom et le type se trouvent en haut, les étiquettes se trouvent dans la section "À propos". Assurez-vous qu'il n'y a pas de fautes d'orthographe dans les noms ou les valeurs des étiquettes.

Vérifiez que la syntaxe de la requête d'étendue est correcte :

. Ouvrez la vue d'exploration, via Vues dans le menu et le bouton bleu "Explorer" à droite. Ou directement via l'URL : `https://<your-stackstate-instance>/#/views/explore`
. Ouvrez les filtres et sélectionnez `switch to STQL`
. Copiez/collez maintenant la requête du champ d'application dans le champ STQL et exécutez la requête.

La vue d'ensemble montre maintenant tous les composants qui correspondent à la requête et qui recevront le graphique.

== Le graphique métrique d'un composant reste vide ("pas de données")

Pour le graphique métrique qui n'a pas de données alors que des données étaient attendues, ouvrez l'inspecteur (l'icône dans le coin supérieur droit du graphique). Cliquez sur le bouton "Afficher la requête" pour afficher les requêtes.

Assurez-vous que la requête ne contient plus aucun des paramètres (c'est-à-dire que toutes les valeurs telles que `${tags.cluster-name}` ou `${name}`) ont été remplacées par les valeurs du composant. Si certains paramètres ont été laissés dans la requête, les étiquettes ne sont pas disponibles sur ce composant. Il convient donc de vérifier les noms utilisés (dans cet exemple `cluster-name`) par rapport aux étiquettes disponibles sur le composant. Veillez également à ce qu'il n'y ait pas de fautes de frappe dans les noms.

Si tous les paramètres sont renseignés, il peut y avoir un problème avec la requête PromQL. Pour cela, copiez la requête PromQL et ouvrez l'explorateur de métriques (via le menu principal de {stackstate-product-name}). Collez la requête dans l'explorateur de métriques et exécutez-la. Cela devrait toujours donner un résultat vide.

Soit la mesure n'existe pas, soit elle n'a pas d'étiquette, soit l'étiquette existe mais il n'y a pas de série temporelle correspondant à la valeur. La méthode la plus rapide pour résoudre ce problème est de réécrire la requête en ne conservant que le nom de la métrique et de l'exécuter, si elle donne des résultats, c'est que la métrique existe (donc pas de fautes de frappe). Le résultat du tableau peut également être utilisé pour vérifier que toutes les étiquettes utilisées existent. Veillez également à ce qu'il n'y ait pas de fautes de frappe.

S'il y a des résultats, mais pas pour une valeur spécifique d'une étiquette (par exemple pour l'étiquette `pod_name` ), la requête est correcte mais il n'y a pas de série temporelle pour cette mesure spécifique pour ce composant spécifique. Ce qu'il faut vérifier dans ce cas :

* Les données sont-elles collectées pour ce composant (par l'intermédiaire de l'agent {stackstate-product-name} ou par un autre moyen) ?
* Le composant est-il même en train de rendre compte de la mesure ?

La manière de procéder dépend de la configuration de la collecte des données.
