= Moniteurs
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Vue d'ensemble

SUSE Observability a encodé les meilleures pratiques via des moniteurs. Les moniteurs SUSE Observability ne se contentent pas de surveiller les mesures, les événements ou les journaux, ils peuvent également contrôler la topologie et les métadonnées afin de détecter les problèmes courants et de garantir la conformité et le respect des normes de l'industrie.
En combinant les moniteurs avec notre intelligence de dépannage unique, SUSE Observability détecte rapidement les problèmes liés et conseille sur la manière d'y remédier. Cette approche proactive réduit le risque de problèmes non détectés et permet de maintenir un environnement Kubernetes sain et robuste.
Les surveillances sont accompagnées de guides de remédiation spécifiques à la ressource sur laquelle est alertée et à l'état surveillé pour guider nos utilisateurs dans leur dépannage.

== Contrôler les résultats

Les résultats du contrôle sont affichés à deux endroits :

. Sur les pages de mise en évidence de toutes les ressources pour voir immédiatement ce qui se passe et comment y remédier.
. Sur le panneau latéral droit, si vous sélectionnez un élément de la topologie, vous obtiendrez une indication rapide des problèmes liés à ce composant.

== Guides d'assainissement

Les guides de remédiation sont affichés dans le tiroir d'état du moniteur, qui apparaît si vous ouvrez un moniteur en cliquant sur le message dans la perspective de mise en évidence d'une ressource.

== Voir aussi

* xref:/use/alerting/kubernetes-monitors.adoc[Moniteurs prêts à l'emploi pour Kubernetes]
