= Configuration de SUSE Observability pour les notifications par courrier électronique
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

[CAUTION]
====
Les utilisateurs SaaS de SUSE Observability peuvent utiliser les notifications par courrier électronique sans configuration supplémentaire. Ce guide ne s'applique qu'aux installations auto-hébergées de SUSE Observability qui prévoient d'utiliser le canal de notification par courrier électronique.
====


Avant de pouvoir utiliser le canal de notification par courrier électronique dans SUSE Observability, vous devez d'abord suivre les étapes suivantes :

== Configurer SUSE Observability avec la configuration SMTP

SUSE Observability doit être configuré avec des informations d'identification pour se connecter au serveur SMTP. Vous pouvez le faire en ajoutant ce qui suit au fichier `values.yaml` de votre installation SUSE Observability :

[,yaml]
----
stackstate:
  email:
    enabled: true
    sender: "<stackstate@example.com>"
    server:
      host: "<smtp.example.com>"
      auth:
        username: "<user name>"
        password: "<user password>"
----

Elle utilise le port `587` du serveur SMTP et la commande `STARTTLS` pour établir une connexion sécurisée. Ce sont toutes les autres options qui peuvent être personnalisées :

[,yaml]
----
stackstate:
  email:
    additionalProperties:
      # Add needed Java email properties for your mail server (use string values), defaults are:
      "mail.smtp.auth": "true"
      "mail.smtp.starttls.enable": "true"
    server:
      protocol: smtp
      port: 587
----

=== Utilisation d'un secret externe

Lorsque le nom d'utilisateur et le mot de passe ne peuvent pas être fournis dans les valeurs mais doivent provenir d'un secret externe, xref:/setup/security/external-secrets.adoc#_getting_username_and_password_for_email_sending_from_an_external_secret[procédez comme] suit
