= Dépannage de l'extension
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

Cette section fournit des étapes de dépannage pour tout problème d'interopérabilité entre {stackstate-product-name} et l'extension Rancher UI.

== Collecter un HAR (Http ARchive)

Http ARchive recueille des informations sur les requêtes envoyées par le navigateur à Rancher et {stackstate-product-name}.  Il enregistre également les réponses reçues.
Cette archive est spécifique à la page/l'onglet du navigateur qui contient l'erreur.  Il n'a pas besoin d'accéder aux instances Rancher ou {stackstate-product-name} (bien que leurs journaux puissent être utiles à un stade ultérieur).

* Ouvrez l'onglet *Réseau* dans le panneau "Outils de développement".  Vous pouvez y accéder en utilisant `F12`.  L'onglet réseau affiche un journal de toutes les demandes effectuées.
* Effacez le journal et actualisez la page qui affiche le comportement problématique.
* Il devrait maintenant y avoir un grand nombre de demandes visibles à la fois pour Rancher et pour SUSE Observability.
* Exporter/Télécharger/Enregistrer le HAR - les noms varient d'un navigateur à l'autre.

== La grappe n'est pas observée

Pour que l'état de santé du cluster soit visible dans Rancher, il faut que ces configurations soient alignées :

* Le nom (affiché) du cluster dans l'interface utilisateur de Rancher.
* Le jeu `stackstate.cluster.name` sur l'agent déployé sur le cluster
* Le nom du cluster dans la configuration du stackpack Kubernetes dans SUSE Observability.

Un décalage aura tendance à apparaître comme "aucune donnée reçue" dans la vue d'ensemble du cluster dans Rancher.

== Échec de la connexion

La configuration de SUSE Observability peut parfois ne pas produire de connexion valide dans l'interface utilisateur de Rancher pour les raisons suivantes :

* L'hôte Rancher n'est pas configuré en tant qu'origine autorisée pour SUSE Observability.  Vous pouvez y remédier en l'ajoutant à la liste `stackstate.allowedOrigins` dans les valeurs helm, ou en passant `--set stackstate.allowedOrigins={"https://<rancher-url>"}` à la commande de déploiement.
* SUSE Observability n'est pas accessible depuis le navigateur. Par exemple, le certificat racine n'a pas été installé.