= Exigences
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Vue d'ensemble

La configuration requise pour le <<_client_browser,client SUSE Observability (navigateur)>> se trouve au bas de la page.

=== Compatibilité avec Rancher et Kubernetes
Consultez la page de compatibilité ici xref:setup/install-stackstate/Compatibility Self Hosted.adoc[Compatibilité Rancher/Kubernetes]

=== Besoins en ressources

Il existe différentes options d'installation pour SUSE Observability. Il est possible d'installer SUSE Observability dans une configuration à haute disponibilité (HA) ou à instance unique (non-HA). Il est recommandé de n'utiliser la configuration non-HA qu'à des fins de test. Pour les environnements de production, il est recommandé d'installer SUSE Observability dans une configuration HA. Pour un déploiement de production standard, la carte SUSE Observability Helm permet de déployer de nombreux services dans une configuration redondante avec 3 instances de chaque service.

Le tableau ci-dessous indique les ressources nécessaires pour les différentes options d'installation. Pour la configuration HA, vous pouvez trouver différents profils d'installation en fonction de la taille de l'environnement observé.
Dans ce tableau de dimensionnement, un nœud observé correspond à 4 vCPU et 16 Go de mémoire, soit notre site `default node size`.
Si les nœuds de votre cluster observé sont plus grands, ils peuvent compter pour plusieurs `default nodes`, ainsi un nœud de 12vCPU et 48GB compte pour 3 `default nodes` sous observation lors de la sélection d'un profil.

|===
|  | procès | 10 non-HA | 20 non-HA | 50 non-HA | 100 non-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *Demandes d'unité centrale*
| 7.5
| 7.5
| 10.5
| 15
| 25
| 49
| 62
| 86.5
| 210

| *Limites de l'unité centrale*
| 16
| 16
| 21.5
| 30.5
| 50
| 103
| 128
| 176
| 278

| *Demandes de mémoire*
| 25.5Gi
| 25.5Gi
| 31Gi
| 35Gi
| 54Gi
| 129Gi
| 146Gi
| 164.5Gi
| 259Gi

| *Limites de la mémoire*
| 26Gi
| 26Gi
| 31,5Gi
| 36Gi
| 54Gi
| 133,5Gi
| 150Gi
| 168.5Gi
| 320Gi
|===

[NOTE]
====
Les exigences indiquées pour le profil représentent la quantité totale de ressources nécessaires pour faire fonctionner le serveur Suse Observability.
Pour s'assurer que tous les différents services du serveur Suse Observability peuvent être alloués :

* Pour les installations non HA, la taille recommandée du nœud est de 4VCPU, 8GB
* Pour les installations HA jusqu'à 500 nœuds, la taille minimale recommandée pour les nœuds est de 8VCPU, 16GB.
* Pour les installations HA de 4000 nœuds, la taille minimale recommandée pour les nœuds est de 16VCPU, 32GB.
====


Il s'agit simplement des limites supérieures et inférieures des ressources qui peuvent être consommées par SUSE Observability dans les différentes options d'installation. L'utilisation réelle des ressources dépend des fonctionnalités utilisées, des limites de ressources configurées et des schémas d'utilisation dynamiques, tels que le déploiement ou la mise à l'échelle de DaemonSet. Pour nos clients auto-hébergés, nous recommandons de commencer par les exigences par défaut et de surveiller l'utilisation des ressources des composants de SUSE Observability.

[NOTE]
====
Les exigences minimales n'incluent pas la capacité de mémoire et d'unité centrale supplémentaire pour assurer des mises à jour régulières de l'application.
====


Pour l'installation de SUSE Observability, veuillez suivre les instructions d'installation ci-dessous :

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift]

=== Stockage

SUSE Observability utilise des réclamations de volumes persistants pour les services qui doivent stocker des données. La classe de stockage par défaut du cluster sera utilisée pour tous les services à moins qu'elle ne soit remplacée par des valeurs spécifiées sur la ligne de commande ou dans un fichier `values.yaml`. Tous les services sont fournis avec une taille de volume préconfigurée qui devrait vous permettre de démarrer, mais qui peut être personnalisée ultérieurement à l'aide de variables, si nécessaire.

[NOTE]
====
Pour les environnements de production, NFS n'est pas recommandé ni pris en charge pour le provisionnement du stockage dans SUSE Observability en raison du risque potentiel de corruption des données.
====


Pour nos différents profils d'installation, les exigences de stockage par défaut sont les suivantes :

|===
|  | procès | 10 non-HA | 20 non-HA | 50 non-HA | 100 non-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *Rétention (jours)*
| 3
| 30
| 30
| 30
| 30
| 30
| 30
| 30
| 30

| *Besoin de stockage*
| 125GB
| 280GB
| 420GB
| 420GB
| 600GB
| 2TB
| 2TB
| 2.5TB
| 5.5TB
|===

[NOTE]
====
Les estimations de stockage présentées tiennent compte d'une durée de conservation par défaut de 14 jours pour les installations NONHA et d'un mois pour les installations HA. Pour les instances de test de courte durée, les tailles de stockage peuvent être encore réduites.
====


Pour plus de détails sur les valeurs par défaut utilisées, voir la page xref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[Configurer le stockage].

=== Limites des ressources de l'espace de noms

Il n'est pas recommandé de définir un quota de ressources, car cela peut interférer avec les demandes de ressources. Les ressources requises par SUSE Observability varient en fonction des fonctionnalités utilisées, des limites de ressources configurées et des schémas d'utilisation dynamiques, tels que le déploiement ou la mise à l'échelle de DaemonSet.

S'il est nécessaire de définir un quota de ressources pour votre implémentation, la limite de ressources de l'espace de noms doit être fixée de manière à correspondre aux xref:/setup/install-stackstate/requirements.adoc#_resource_requirements[exigences de taille du] nœud.

== Client (navigateur)

Pour utiliser l'interface graphique de SUSE Observability, vous devez utiliser l'un des navigateurs Web suivants :

* Chrome
* Firefox
