= Jetons de service
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Vue d'ensemble

Grâce aux jetons de service, il est possible de s'authentifier auprès de SUSE Observability sans avoir configuré de compte utilisateur. Ceci est utile dans les situations où vous souhaitez utiliser SUSE Observability à partir de services sans tête tels qu'un serveur CI. Dans un tel scénario, vous ne voulez généralement pas provisionner un compte d'utilisateur dans votre fournisseur d'identité.

== Gérer les jetons de service

Les jetons de service peuvent être gérés via le xref:/setup/cli/cli-sts.adoc[CLI de`sts` ]. Les commandes suivantes sont disponibles :

[,bash]
----
> sts service-token --help
Manage service tokens.

Usage:
  sts service-token [command]

Available Commands:
  create      Create a service token
  delete      Delete a service token
  list        List service tokens

Use "sts service-token [command] --help" for more information about a command.
----

Il est également possible de configurer <<_set_up_a_bootstrap_service_token,un jeton de service de démarrage>> lors de l'installation de SUSE Observability.

=== Créer des jetons de service

Pour créer un jeton de service pour une instance installée de SUSE Observability, vous pouvez utiliser la nouvelle CLI `sts`.

[,sh]
----
sts service-token create
----

[NOTE]
====
Notez que le jeton de service ne sera affiché qu'une seule fois. Il n'est pas possible de revoir le jeton.
====


Cette commande prend en compte les arguments de ligne de commande suivants :

|===
| Drapeau | Description

| `--name`
| Le nom du jeton de service

| `--expiration`
| La date d'expiration du jeton de service, au format aaaa-MM-jj. L'expiration est facultative.

| `--roles`
| Une liste de rôles séparés par des virgules à attribuer au jeton de service
|===

Par exemple, la commande ci-dessous créera un jeton de service avec le nom `my-service-token` et le rôle `stackstate-power-user`:

[,sh]
----
> sts service-token create --name my-service-token --roles stackstate-power-user
✅ Service token created: svctok-aaaaa-bbbb-ccccc-ddddd
----

=== Mise en place d'un jeton de service d'amorçage

Lors de l'installation de SUSE Observability, il est possible de l'amorcer avec un jeton de service (temporaire). Cela permet d'utiliser l'interface de commande sans avoir à interagir avec SUSE Observability et à obtenir un jeton d'API à partir de l'interface utilisateur. Pour ce faire, vous pouvez ajouter l'extrait suivant au fichier de configuration de SUSE Observability :

Pour configurer SUSE Observability afin de créer un jeton de service bootstrap sur Kubernetes, les valeurs suivantes doivent être ajoutées au fichier `authentication.yaml`. Par exemple

[,yaml]
----
stackstate:
  authentication:
    serviceToken:
      bootstrap:
        token: <token>
        roles:
          - stackstate-power-user
        ttl: 24h
----

Suivez les étapes ci-dessous pour configurer SUSE Observability afin de créer un jeton de service bootstrap :

. Dans `authentication.yaml` - ajoutez le jeton d'amorçage :
 ** *token* - Le token qui sera créé lors du démarrage (initial) de SUSE Observability.
 ** *roles* - Tableau des rôles qui seront attribués au jeton d'amorçage.
 ** *ttl* - Facultatif. Durée de vie du jeton de service, exprimée sous la forme d'une chaîne de durée.
. Stockez le fichier `authentication.yaml` avec le fichier `values.yaml` des instructions d'installation de SUSE Observability.
. Exécutez une mise à jour de Helm pour appliquer les changements.
+
[,text]
----
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values values.yaml \
   --values authentication.yaml \
 suse-observability \
 suse-observability/suse-observability
----

[NOTE]
====
*Remarque :*

* La première exécution de la commande helm upgrade entraînera le redémarrage des pods, ce qui peut provoquer une brève interruption de la disponibilité.
* Inclure `authentication.yaml` dans chaque course `helm upgrade`.
* La configuration d'authentification est stockée en tant que secret Kubernetes.
====


==== Configurer le jeton du service d'amorçage à partir d'un secret externe

Lorsque le jeton d'amorçage doit provenir d'un secret externe, suivez xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[ces étapes] et ajoutez les données suivantes :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  bootstrap_token: <base64 of token>
----

Ce jeton peut être ajouté au secret à côté des données qui s'y trouvent déjà.

=== Liste des jetons de service

L'ID, le nom, la date d'expiration et les rôles de tous les jetons de service créés peuvent être consultés à l'aide du nouveau CLI `sts`. Par exemple :

[,bash]
----
> sts service-token list
ID              | NAME             | EXPIRATION | ROLES
107484341630693 | my-service-token |            | [stackstate-power-user]
----

=== Supprimer les jetons de service

Un jeton de service peut être supprimé à l'aide de la nouvelle CLI `sts`. Passez l'ID du jeton de service en argument. Par exemple :

[,bash]
----
> sts service-token delete 107484341630693
✅ Service token deleted: 107484341630693
----

== Utiliser des jetons de service

Une fois créé, un jeton de service peut être utilisé pour s'authentifier auprès de SUSE Observability à partir d'un service sans tête. Pour ce faire, vous pouvez utiliser l'interface de programmation ou vous adresser directement à l'API.

=== SUSE Observability `sts` CLI

Un jeton de service peut être utilisé pour l'authentification avec le CLI `sts`. Pour plus de détails, voir xref:/setup/cli/cli-sts.adoc#_authentication[la documentation CLI.]

=== SUSE Observability APIs

Pour utiliser un jeton de service afin de communiquer directement avec l'API de base SUSE Observability, ajoutez-le à l'en-tête de la requête de l'une des manières suivantes :

* Dans l'en-tête `Authorization`:
+
[,bash]
----
  > curl -X GET -H "Authorization: ApiKey <TOKEN>" http://localhost:8080/api/server/status
----

* Dans l'en-tête `X-API-Key`:
+
[,bash]
----
  > curl -X GET -H "X-API-Key: <TOKEN>" http://localhost:8080/api/server/status
----

➡️ xref:/setup/cli/cli-sts.adoc#_authentication[En savoir plus sur les API de SUSE Observability]
