= Mot de passe unique
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

Au départ, SUSE Observability est configuré avec un seul mot de passe, xref:/k8s-suse-rancher-prime.adoc#_installation[configuré lors de l'installation]. Cela permet d'authentifier les utilisateurs à l'aide d'un mot de passe unique, généré de manière aléatoire et créé par le diagramme `suse-observability-values`.
La valeur du mot de passe peut être trouvée comme commentaire dans le fichier généré `suse-observability-values/templates/baseConfig_values.yaml`.

Cette configuration prévoit un utilisateur administrateur avec le mot de passe généré.

Cette méthode de fourniture d'un mot de passe convient pour démarrer, mais pour la production, il est recommandé d'utiliser l'une des autres xref:/setup/security/authentication/authentication_options.adoc[options d'authentification].

== Définition du mot de passe unique à l'aide du tableau des valeurs

Pour définir un mot de passe alternatif xref:/k8s-suse-rancher-prime.adoc#_installation[pendant l']installation, ajoutez la ligne suivante à la commande de génération de valeurs pendant l'installation :

[,bash]
----
helm template \
  ...
  --set adminPassword='<password>' \
  ...
  suse-observability-values \
  suse-observability/suse-observability-values --output-dir $VALUES_DIR
----

== Définition du mot de passe unique dans le tableau de bord

Il est également possible de définir le mot de passe unique directement dans l'invocation de l'installation de helm. Pour ce faire, il faut créer une chaîne cryptée du mot de passe requis, à l'aide de `htpasswd -bnBC 10 "" <password> | tr -d ':\n'` ou d'un outil en ligne.
Le remplir dans l'invocation de la barre ou dans des valeurs séparées.yaml.

[,bash]
----
helm install \
  ...
  --set stackstate.authentication.adminPassword='<bcrypted_password>' \
  ...
  suse-observability \
  suse-observability/suse-observability --output-dir $VALUES_DIR
----

=== Utilisation d'un secret externe

Lorsque le mot de passe unique doit provenir d'un secret externe, suivez xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[ces étapes] mais complétez les données suivantes :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of bcrypted password>
----

La création d'une version cryptée d'un mot de passe peut être réalisée à l'aide de `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`.

== Voir aussi

* xref:/setup/security/authentication/authentication_options.adoc[Options d'authentification]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissions pour les rôles prédéfinis de SUSE Observability]
* xref:/setup/security/rbac/rbac_roles.adoc[Créer des rôles RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Secrets externes]
