= k8s Custom Secret Management
:revdate: 2025-10-27
:page-revdate: {revdate}

== Vue d'ensemble

SUSE Observability Agent prend en charge la spécification du nom d'un secret personnalisé qui contient la clé API et le jeton d'autorisation du cluster. Cette fonction est utile pour les utilisateurs qui souhaitent gérer leurs propres secrets et éviter la création automatique de secrets par le diagramme Helm.

NOTE: *Il existait une méthode antérieure pour spécifier ceci qui est maintenant obsolète, voir la xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[méthode obsolète].*

== La carte du gouvernail

=== Options de configuration

* `global.apiKey.fromSecret`: Spécifier un nom de secret préexistant résidant dans le même espace de noms et contenant un champ `STS_API_KEY` contenant la clé d'api.
* `global.clusterAgentAuthToken.fromSecret`: Spécifier un nom secret préexistant résidant dans le même espace de noms qui contient un champ `STS_CLUSTER_AGENT_AUTH_TOKEN` contenant un jeton pour sécuriser les connexions entre le cluster et les agents de nœuds.

=== Behavior Description

* *Création automatique de secrets*: Par défaut, le graphique exige qu'une adresse `stackstate.apiKey` soit spécifiée et crée lui-même un secret. Le site `STS_CLUSTER_AGENT_AUTH_TOKEN` est généré automatiquement.
* *Gestion personnalisée des secrets*: En remplaçant les champs `fromSecret`, la clé d'api et le jeton d'authentification du cluster seront extraits de ces secrets.
* *Omission implicite*: Si vous indiquez que vous souhaitez gérer vos propres secrets, le tableau ne tiendra pas compte des valeurs pour `stackstate.apiKey` et `stackstate.cluster.authToken`.

== Comment l'utiliser dans values.yaml

. *Utilisation de la création automatique de secrets (par défaut)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Gérer ses propres secrets*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
