= k8s Custom Secrets Setup (Déclassé)
:revdate: 2025-10-27
:page-revdate: {revdate}

== Vue d'ensemble

L'agent SUSE Observability prend en charge la spécification du nom d'un secret personnalisé qui contient la clé API et le jeton d'autorisation du cluster. Cette fonction est utile pour les utilisateurs qui souhaitent gérer leurs propres secrets et éviter la création automatique de secrets par le diagramme Helm.

[CAUTION]
====
*Cette méthode de personnalisation des secrets est obsolète et incompatible avec la fonction RBAC.*

Veuillez utiliser la xref:/setup/agent/k8s-custom-secrets-setup.adoc[nouvelle méthode d'] utilisation des secrets externes.
====


== La carte du gouvernail

=== Options de configuration

* `stackstate.manageOwnSecrets`: Un indicateur booléen qui détermine si l'utilisateur souhaite gérer ses propres secrets. La valeur par défaut est `false`.
* `stackstate.customSecretName`: (Facultatif) Nom du secret personnalisé à créer par l'utilisateur. Requis si `stackstate.manageOwnSecrets` est défini sur `true`.
* `stackstate.customApiKeySecretKey`: (Facultatif) Nom de la clé de l'API dans le secret personnalisé. Requis si `stackstate.manageOwnSecrets` est défini sur `true`.
* `stackstate.customClusterAuthTokenSecretKey`: (Facultatif) Nom de la clé du jeton d'autorisation du cluster dans le secret personnalisé. Requis si `stackstate.manageOwnSecrets` est défini sur `true`.

=== Behavior Description

* *Création automatique de secrets*: Par défaut, le graphique continue à créer automatiquement des secrets comme auparavant si `stackstate.manageOwnSecrets` est réglé sur `false`.
* *Gestion personnalisée des secrets*: Si `stackstate.manageOwnSecrets` est défini sur `true`, la carte attend de l'utilisateur qu'il fournisse le nom du secret personnalisé (`stackstate.customSecretName`) ainsi que les clés pour la clé API et le jeton d'autorisation (`stackstate.customApiKeySecretKey` et `stackstate.customClusterAuthTokenSecretKey`, respectivement).
* *Omission implicite*: Si vous indiquez que vous souhaitez gérer vos propres secrets, le tableau ne tiendra pas compte des valeurs pour `stackstate.apiKey` et `stackstate.cluster.authToken`.
+
== Comment l'utiliser dans values.yaml

. *Utilisation de la création automatique de secrets (par défaut)*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *Gérer ses propres secrets*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
