= Certificats pour la traçabilité des requêtes injection de sidecar
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Le xref:/setup/agent/k8sTs-agent-request-tracing.adoc#_enabling_the_trace_header_injection_sidecar[mécanisme d'injection de sidecar], qui est activé lors de l'utilisation de `--set httpHeaderInjectorWebhook.enabled=true` lors de l'installation de l'agent, crée un certificat auto-signé et utilise un `ClusterRole` qui accorde un accès en écriture aux objets `Secret` et `MutatingWebhookConfiguration` dans le cluster Kubernetes.

Si, pour des raisons de sécurité, il n'est pas souhaitable de créer `ClusterRoles` qui accorde des droits d'écriture à l'échelle du cluster, ou s'il existe d'autres moyens de fournir un certificat :

. Générer <<_generate_a_certificate_locally,localement>> un certificat auto-signé.
. Utilisez le k8s https://cert-manager.io/[cert-manager] (s'il existe déjà sur le cluster) <<_generate_a_certificate_using_the_cert_manager,avec un `ClusterIssuer`>>.

== Générer un certificat localement

Pour générer un certificat localement, procédez comme suit :

. Téléchargez le script de génération de certificat et exécutez-le pour produire un fichier de valeurs de barre (`tls_values.yaml`) avec le bon certificat :
+
----
wget https://raw.githubusercontent.com/StackVista/http-header-injector/main/scripts/generate_ca_cert.sh
chmod +x generate_ca_cert.sh
./generate_ca_cert.sh <helm-agent-release-name> <helm-agent-namespace>
----
+
Veillez à utiliser le nom de version qui sera utilisé dans la commande helm et l'espace de noms, sinon le certificat ne sera pas valide.

. Installer l'agent en ajoutant la configuration supplémentaire en ajoutant `--set httpHeaderInjectorWebhook.enabled=true -f tls_values.yaml` à la commande d'invocation de helm

== Générer un certificat à l'aide du gestionnaire de certificats

Si le https://cert-manager.io/[cert-manager] est installé dans votre cluster et qu'un `ClusterIssuer` est configuré, il est possible d'utiliser le certificat émis par le `ClusterIssuer` dans l'agent de l'injecteur sidecar. Pour ce faire, ajoutez les arguments de ligne de commande suivants pour installer l'agent : `--set httpHeaderInjectorWebhook.enabled=true --set-string httpHeaderInjectorWebhook.webhook.tls.mode="cert-manager" --set-string httpHeaderInjectorWebhook.webhook.tls.certManager.issuer="<my-cluster-issuer>"`. Veillez à remplacer my-cluster-issuer par le nom de l'émetteur de votre cluster.
