= Remplacer la configuration par défaut
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

Un certain nombre de valeurs peuvent être définies dans le https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[graphique] SUSE. Par exemple, il est possible de personnaliser les `tolerations` et `nodeSelectors` pour chacun des composants. Vous pouvez également ajouter une configuration personnalisée et inclure des variables d'environnement.

== Configuration personnalisée pour SUSE Observability `api`

Pour le service SUSE Observability `api`, la configuration personnalisée peut être déposée directement dans le graphique Helm. C'est la meilleure façon de remplacer la configuration par défaut de SUSE Observability et c'est particulièrement pratique pour personnaliser l'authentification. La configuration ainsi définie sera disponible dans le fichier de configuration de SUSE Observability au format https://github.com/lightbend/config/blob/master/HOCON.md[] HOCON.

Par exemple, vous pouvez définir un "lien de mot de passe oublié" personnalisé pour la page de connexion de SUSE Observability :

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      config: |
        stackstate.api.authentication.forgotPasswordLink =
        "https://www.stackstate.com/forgotPassword.html"
----

--
====

[NOTE]
====
Notez que la configuration personnalisée définie ici sera remplacée par les xref:/setup/install-stackstate/kubernetes_openshift/customize_config.adoc#_environment_variables[variables d'environnement].
====


== Variables d'environnement

La configuration de tous les services SUSE Observability (`receiver`, `k2es-*`, `correlation` et `api`) peut être personnalisée à l'aide de variables d'environnement. Les variables d'environnement sont spécifiées dans le fichier `values.yaml` et peuvent être soit `secret` (comme les mots de passe), soit `open` (pour les valeurs normales). Pour convertir un élément de configuration en nom de variable d'environnement, remplacez `.` par `_` et ajoutez le préfixe `CONFIG_FORCE_`.

[,text]
----
# configuration item
stackstate.api.authentication.forgotPasswordLink

# environment variable name
CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink
----

Par exemple, vous pouvez définir un "lien de mot de passe oublié" personnalisé pour la page de connexion de SUSE Observability :

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      extraEnv:
        # The value for open env vars is defined on the deployment
        open:
          CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink: "https://www.stackstate.com/forgotPassword.html"
        # The value for secret env vars is defined in a secret and referenced from the deployment
        secret:
          CONFIG_FORCE_stackstate_authentication_adminPassword: "d8e8fca2dc0f896fd7cb4cb0031ba249"
----

--
====

[NOTE]
====
Pour le service SUSE Observability `api`, les variables d'environnement remplaceront la <<_custom_configuration_for_suse_observability_api,configuration personnalisée définie à l'aide de `config`>>.
====


* Tous les détails sur le nommage des différents services se trouvent dans le https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[readme de] SUSE
* Plus de détails sur la xref:/setup/security/authentication/README.adoc[personnalisation de l'authentification].
