= Désinstaller SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Vue d'ensemble

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[Désinstaller le chariot Helm]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Supprimer les ressources restantes]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_manually_created_resources[Supprimer les ressources créées manuellement]

== Désinstaller la carte Helm

[NOTE]
====
La désinstallation de la carte helm préservera toutes les données, car helm ne supprimera pas les réclamations relatives au volume persistant ni l'espace de noms. Pour les supprimer, il faut également xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[supprimer les ressources restantes].
====


Pour désinstaller SUSE Observability, la première chose à faire est d'exécuter la commande `helm uninstall`. Cette commande supprimera toutes les ressources créées par la commande `helm upgrade --install`.

Désinstallez la version `suse-observability` de l'espace de noms `suse-observability` comme ceci, remplacez le nom de l'espace de noms ou de la version par tout nom personnalisé utilisé lors de l'installation :

----
helm uninstall --namespace suse-observability suse-observability
----

La commande reviendra presque immédiatement, mais l'arrêt de tous les pods et la suppression de toutes les autres ressources peuvent prendre un certain temps. Vérifier que toutes les cosses ont disparu :

----
kubectl get pods --namespace suse-observability
----

Si vous souhaitez réinstaller SUSE Observability ultérieurement et conserver les anciennes données, c'est tout. Pour une désinstallation complète, continuez avec les deux sections suivantes.

== Supprimer les ressources restantes

[CAUTION]
====
La suppression des réclamations relatives au volume persistant et/ou de l'espace de noms entraînera la perte de toutes les données stockées dans SUSE Observability.
====


Pour supprimer l'espace de noms et, par conséquent, les réclamations de volumes persistants et les volumes persistants qui leur sont liés, il suffit de supprimer l'ensemble de l'espace de noms :

----
kubectl delete namespace suse-observability
----

Lorsque la commande revient, l'espace de noms et tous les volumes auront été supprimés.

Pour ne supprimer que les réclamations de volumes persistants (PVC) et conserver l'exécution de l'espace de noms :

----
kubectl delete pvc --all -n suse-observability
----

Sur OpenShift, le diagramme Helm a également créé une contrainte de contexte de sécurité (SCC). Il n'est pas nettoyé automatiquement par Helm mais doit être supprimé manuellement :

----
# The scc is always named suse-observability-<namespace>
oc delete scc suse-observability-suse-observability
----

== Supprimer les ressources créées manuellement

[NOTE]
====
Même si vous avez l'intention de réinstaller SUSE Observability sur le même cluster mais dans un espace de noms différent, vous pouvez les supprimer. Les ressources contiennent des références à l'espace de noms SUSE Observability.
====


Comme décrit dans les xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_manually_create_cluster_wide_resources[autorisations requises], il a pu être nécessaire que votre administrateur de cluster crée certaines ressources manuellement. Ces ressources peuvent maintenant être supprimées à nouveau, mais il s'agit également d'une tâche manuelle qui nécessite l'autorisation de l'administrateur.

Supprimez le rôle de cluster et les liaisons de rôle de cluster qui ont été créés de cette manière :

----
kubectl delete cluster-role suse-observability-authorization
kubectl delete cluster-role-binding suse-observability-authorization
kubectl delete cluster-role-binding suse-observability-authentication
----
