= Activer les sauvegardes
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

[NOTE]
====
Cette page s'applique à {stackstate-product-name} v2.7.0 ou plus récent.
====

== Vue d'ensemble

{stackstate-product-name} dispose d'un mécanisme de sauvegarde intégré qui peut être configuré pour stocker les sauvegardes sur AWS S3, Azure Blob Storage ou un volume persistant Kubernetes.

La plupart des sauvegardes sont activées avec une seule valeur Helm `global.backup.enabled`. Les sauvegardes des paramètres sont toujours activées mais se comportent différemment en fonction des valeurs suivantes :

=== Champ d'application de la sauvegarde

Les données suivantes peuvent être sauvegardées automatiquement :

* *Paramètres* (StackPacks, moniteurs, vues, jetons) - toujours activés :
** Lorsque `global.backup.enabled` est `true`: les sauvegardes sont stockées via MinIO dans votre système de stockage configuré.
** Lorsque `global.backup.enabled` est `false`: les sauvegardes sont stockées sur un volume persistant Kubernetes dédié, en contournant MinIO.
* *Données topologiques et paramètres* stockés dans StackGraph - activé lorsque `global.backup.enabled` est `true`
* *Métriques* stockées dans l'instance Victoria Metrics de {stackstate-product-name}- activée lorsque `global.backup.enabled` est `true`
* *Données télémétriques* stockées dans l'instance Elasticsearch de {stackstate-product-name}- activées lorsque `global.backup.enabled` est `true`
* *Données OpenTelemetry* stockées dans l'instance ClickHouse de {stackstate-product-name}- activées lorsque `global.backup.enabled` est `true`

=== Options de stockage

Les sauvegardes utilisent https://min.io/[MinIO (min.io)] comme passerelle compatible S3 vers votre backend de stockage. MinIO est automatiquement déployé par la carte Helm lorsque les sauvegardes sont activées.

L'instance MinIO intégrée peut être configurée pour stocker les sauvegardes à trois endroits :

* xref:/setup/data-management/backup_restore/backup_enable.adoc[AWS S3]
* xref:/setup/data-management/backup_restore/backup_enable.adoc[Stockage Azure Blob]
* xref:/setup/data-management/backup_restore/backup_enable.adoc[Stockage Kubernetes]

== Activer les sauvegardes

=== AWS S3

[CAUTION]
====

*Cryptage*

Les clés gérées par Amazon S3 (SSE-S3) doivent être utilisées pour chiffrer les buckets S3 qui stockent les sauvegardes.

⚠️ Le chiffrement avec des clés AWS KMS stockées dans AWS Key Management Service (SSE-KMS) n'est pas pris en charge. Cela entraînera des erreurs telles que celle-ci dans les journaux d'Elasticsearch :

`Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: ZX4D/ZDUzZWRhNDUyZTI1MTc= in base 64) didn't match hash (etag: c75faa31280154027542f6530c9e543e in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@5481a656, bucketName: suse-observability-elasticsearch-backup, key: tests-UG34QIV9s32tTzQWdPsZL/master.dat)\",`
====


==== Utilisation de buckets S3 distincts

Pour activer les sauvegardes planifiées vers des buckets AWS S3 distincts (un par datastore), ajoutez le fragment YAML suivant au fichier Helm `values.yaml` utilisé pour installer {stackstate-product-name}:

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  stackGraph:
    bucketName: AWS_STACKGRAPH_BUCKET
  elasticsearch:
    bucketName: AWS_ELASTICSEARCH_BUCKET
  configuration:
    bucketName: AWS_CONFIGURATION_BUCKET
victoria-metrics-0:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
victoria-metrics-1:
  backup:
    bucketName: AWS_VICTORIA_METRICS_BUCKET
clickhouse:
  backup:
    bucketName: AWS_CLICKHOUSE_BUCKET
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  s3gateway:
    enabled: true
    accessKey: AWS_ACCESS_KEY
    secretKey: AWS_SECRET_KEY
----

Remplacer les valeurs suivantes :

* `YOUR_ACCESS_KEY` et `YOUR_SECRET_KEY` sont les identifiants qui seront utilisés pour sécuriser le système MinIO. Ces informations d'identification sont définies sur le système MinIO et utilisées par les tâches de sauvegarde automatique et les tâches de restauration. Ils sont également nécessaires si vous souhaitez accéder manuellement au système MinIO.
 ** YOUR_ACCESS_KEY doit contenir de 5 à 20 caractères alphanumériques.
 ** YOUR_SECRET_KEY doit contenir de 8 à 40 caractères alphanumériques.
* `AWS_ACCESS_KEY` et `AWS_SECRET_KEY` sont les identifiants AWS de l'utilisateur IAM qui a accès aux buckets S3 où les sauvegardes seront stockées. Voir ci-dessous la politique d'autorisation qui doit être attachée à cet utilisateur.
* `AWS_*_BUCKET` sont les noms des buckets S3 dans lesquels les sauvegardes doivent être stockées.
+
[Note]
====
Les noms des buckets AWS S3 sont globaux pour l'ensemble d'AWS. Par conséquent, les buckets S3, avec le nom par défaut (`sts-elasticsearch-backup`, `sts-configuration-backup`, `sts-stackgraph-backup`, `sts-victoria-metrics-backup` et `sts-clickhouse-backup` ), ne seront probablement pas disponibles.
====

==== Utilisation d'un seul seau S3 avec préfixes

Au lieu d'utiliser des buckets distincts pour chaque datastore, vous pouvez utiliser un seul bucket S3 avec des préfixes différents :

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  elasticsearch:
    bucketName: BUCKET
    s3Prefix: elasticsearch
  stackGraph:
    bucketName: BUCKET
    s3Prefix: stackgraph
  configuration:
    bucketName: BUCKET
    s3Prefix: configuration
victoria-metrics-0:
  backup:
    bucketName: BUCKET
    s3Prefix: victoria-metrics-0
victoria-metrics-1:
  backup:
    bucketName: BUCKET
    s3Prefix: victoria-metrics-1
clickhouse:
  backup:
    bucketName: BUCKET
    s3Prefix: clickhouse
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  s3gateway:
    enabled: true
    accessKey: AWS_ACCESS_KEY
    secretKey: AWS_SECRET_KEY
----

Remplacez `BUCKET` par le nom de votre panier S3. Les sauvegardes des différents datastores sont organisées en utilisant les valeurs configurées de `s3Prefix`. Les valeurs `YOUR_ACCESS_KEY`, `YOUR_SECRET_KEY`, `AWS_ACCESS_KEY`, et `AWS_SECRET_KEY` de la section précédente s'appliquent ici.

=== Permissions AWS S3

L'utilisateur IAM identifié par `AWS_ACCESS_KEY` et `AWS_SECRET_KEY` doit être configuré avec la politique de permission suivante pour accéder aux buckets S3 :

[,javascript]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowListMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        },
        {
            "Sid": "AllowWriteMinioBackupBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::AWS_STACKGRAPH_BUCKET/*",
                "arn:aws:s3:::AWS_ELASTICSEARCH_BUCKET/*",
                "arn:aws:s3:::AWS_VICTORIA_METRICS_BUCKET/*",
                "arn:aws:s3:::AWS_CLICKHOUSE_BUCKET/*",
                "arn:aws:s3:::AWS_CONFIGURATION_BUCKET"
            ]
        }
    ]
}
----

=== Stockage Azure Blob

==== Utilisation de récipients séparés

Pour activer les sauvegardes vers des conteneurs Azure Blob Storage distincts (un par datastore), ajoutez le fragment YAML suivant au fichier Helm `values.yaml` utilisé pour installer {stackstate-product-name}:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: AZURE_STORAGE_ACCOUNT_NAME
  secretKey: AZURE_STORAGE_ACCOUNT_KEY
  azuregateway:
    enabled: true
----

Remplacer les valeurs suivantes :

* `AZURE_STORAGE_ACCOUNT_NAME` - le https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[nom du compte de stockage Azure]
* `AZURE_STORAGE_ACCOUNT_KEY` - la https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal[clé du compte de stockage Azure] où les sauvegardes doivent être stockées.

Les sauvegardes StackGraph, Elasticsearch, Victoria Metrics et ClickHouse sont stockées dans des conteneurs BLOB appelés respectivement `sts-stackgraph-backup`, `sts-configuration-backup`, `sts-elasticsearch-backup`, `sts-victoria-metrics-backup`, `sts-clickhouse-backup`. Ces noms peuvent être modifiés en définissant les valeurs du Helm `backup.stackGraph.bucketName`, `backup.elasticsearch.bucketName`, `victoria-metrics-0.backup.bucketName`, `victoria-metrics-1.backup.bucketName` et `clickhouse.backup.bucketName` respectivement.

==== Utilisation d'un seul conteneur avec des préfixes

Au lieu d'utiliser des conteneurs distincts pour chaque magasin de données, vous pouvez utiliser un seul conteneur Azure Blob Storage avec différents préfixes :

[,yaml]
----
global:
  backup:
    enabled: true
backup:
  elasticsearch:
    bucketName: CONTAINER
    s3Prefix: elasticsearch
  stackGraph:
    bucketName: CONTAINER
    s3Prefix: stackgraph
  configuration:
    bucketName: CONTAINER
    s3Prefix: configuration
victoria-metrics-0:
  backup:
    bucketName: CONTAINER
    s3Prefix: victoria-metrics-0
victoria-metrics-1:
  backup:
    bucketName: CONTAINER
    s3Prefix: victoria-metrics-1
clickhouse:
  backup:
    bucketName: CONTAINER
    s3Prefix: clickhouse
minio:
  accessKey: AZURE_STORAGE_ACCOUNT_NAME
  secretKey: AZURE_STORAGE_ACCOUNT_KEY
  azuregateway:
    enabled: true
----

Remplacez `CONTAINER` par le nom de votre conteneur Azure Blob Storage. Les sauvegardes pour les différents datastores seront organisées en utilisant les valeurs `s3Prefix` configurées. Les valeurs `AZURE_STORAGE_ACCOUNT_NAME` et `AZURE_STORAGE_ACCOUNT_KEY` de la section précédente s'appliquent ici.

=== Volume persistant Kubernetes

[CAUTION]
====
L'utilisation des volumes persistants Kubernetes pour les sauvegardes présente des limites importantes :

* Coûteux - Les fournisseurs de services en nuage utilisent généralement le stockage en bloc (EBS/Azure Block), ce qui est coûteux pour les sauvegardes volumineuses.
* Pas de reprise après sinistre - les PV sont détruits si la grappe est supprimée.
* Non portable - Impossible de restaurer les sauvegardes vers un autre cluster

**Recommandation :** Utilisez plutôt AWS S3 ou Azure Blob Storage pour les environnements de production.
====

==== Configuration de base

Pour activer les sauvegardes sur le stockage local du cluster, activez MinIO en ajoutant le fragment YAML suivant au fichier Helm `values.yaml` utilisé pour installer {stackstate-product-name}:

[,yaml]
----
global:
  backup:
    enabled: true
minio:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  persistence:
    enabled: true
----

Remplacer les valeurs suivantes :

* `YOUR_ACCESS_KEY` et `YOUR_SECRET_KEY` - les informations d'identification qui seront utilisées pour sécuriser le système MinIO. Les tâches de sauvegarde automatique et les tâches de restauration les utiliseront. Ils sont également tenus d'accéder manuellement au stockage MinIO. `YOUR_ACCESS_KEY` doit contenir de 5 à 20 caractères alphanumériques et `YOUR_SECRET_KEY` de 8 à 40 caractères alphanumériques.

== Données de configuration et de topologie (StackGraph)

Les sauvegardes des données de configuration et de topologie (StackGraph) sont des sauvegardes complètes, stockées dans un fichier unique portant l'extension `.graph`. Chaque fichier contient une sauvegarde complète et peut être déplacé, copié ou supprimé selon les besoins.

=== Calendrier des sauvegardes

Par défaut, les sauvegardes de StackGraph sont créées quotidiennement à 03h00, heure du serveur.

Le calendrier de sauvegarde peut être configuré à l'aide de la valeur Helm `backup.stackGraph.scheduled.schedule`, spécifiée dans https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#_cron_schedule_syntax[cron schedule syntax (kubernetes.io)] Kubernetes.

=== Conservation des sauvegardes

Par défaut, les sauvegardes de StackGraph sont conservées pendant 30 jours. Comme les sauvegardes de StackGraph sont des sauvegardes complètes, cela peut nécessiter beaucoup d'espace de stockage.

Le delta de rétention des sauvegardes peut être configuré à l'aide de la valeur Helm `backup.stackGraph.scheduled.backupRetentionTimeDelta`, spécifiée dans le format de l'argument de la date GNU `--date`. La valeur par défaut est `30 days ago`. Voir https://www.gnu.org/software/coreutils/manual/html_node/Relative-items-in-date-strings.html[Éléments relatifs dans les chaînes de dates] pour plus d'exemples.

=== Désactiver les sauvegardes programmées

Pour désactiver les sauvegardes planifiées de StackGraph, définissez la planification des sauvegardes à une date éloignée dans le temps à l'aide de la valeur Helm `backup.stackGraph.scheduled.schedule`:

[,yaml]
----
backup:
  stackGraph:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Paramètres

Settings (Configuration previously) inclut les instances installées de StackPacks avec leur configuration et d'autres personnalisations créées par l'utilisateur, telles que les moniteurs, les vues personnalisées et les jetons de service.

Les sauvegardes des paramètres sont légères (généralement quelques mégaoctets seulement) et rapides à restaurer avec un temps d'arrêt minimal. Après la restauration d'une sauvegarde des paramètres, les nouvelles données seront traitées comme auparavant, recréant la topologie, les états de santé et les alertes. Cependant, l'historique de la topologie (y compris la santé) n'est pas préservé dans les sauvegardes des paramètres - pour cela, utilisez la sauvegarde StackGraph décrite ci-dessus.

[NOTE]
====
*Les sauvegardes de paramètres sont toujours activées*, quelle que soit la valeur de `global.backup.enabled`:

* Quand `global.backup.enabled` est `true`: Les sauvegardes des paramètres sont stockées via MinIO dans votre backend de stockage configuré (AWS S3, Azure Blob Storage ou Kubernetes Persistent Volume).
* Quand `global.backup.enabled` est `false`: Les sauvegardes des paramètres sont stockées sur un volume persistant Kubernetes dédié, en contournant MinIO.
====

=== Calendrier des sauvegardes

Par défaut, les sauvegardes des paramètres sont créées quotidiennement à 04h00, heure du serveur.

Le calendrier de sauvegarde peut être configuré à l'aide de la valeur Helm `backup.configuration.scheduled.schedule`, spécifiée dans https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#_cron_schedule_syntax[cron schedule syntax (kubernetes.io)] Kubernetes.

=== Conservation des sauvegardes

La conservation des sauvegardes dépend du paramètre `global.backup.enabled`:

**Lorsque `global.backup.enabled` est `true`** (sauvegardes stockées via MinIO) :

* Par défaut, les sauvegardes des paramètres sont conservées pendant 365 jours.
* Configurer la rétention en utilisant `backup.configuration.scheduled.backupRetentionTimeDelta` - spécifié dans le format de l'argument de la date GNU `--date`. La valeur par défaut est `365 days ago`

**Lorsque `global.backup.enabled` est `false`** (sauvegardes stockées sur un PV dédié) :

* Par défaut, les 10 derniers fichiers de sauvegarde sont conservés sur le volume persistant.
* Configurer le nombre maximum de fichiers en utilisant `backup.configuration.maxLocalFiles` (par défaut : `10`)
* Configurer la taille du PV en utilisant `backup.configuration.scheduled.pvc.size` (par défaut : `1Gi`)

Exemple de configuration pour un stockage photovoltaïque dédié :

[,yaml]
----
backup:
  configuration:
    maxLocalFiles: 10
    scheduled:
      pvc:
        size: '1Gi'
----

=== Désactiver les sauvegardes programmées

Pour désactiver les sauvegardes programmées des paramètres, définissez le calendrier des sauvegardes à une date éloignée dans le temps à l'aide de la valeur Helm `backup.configuration.scheduled.schedule`:

[,yaml]
----
backup:
  configuration:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Métriques (Victoria Metrics)

Victoria Metrics crée des sauvegardes en prenant un instantané des données métriques actuelles et en ne stockant que les modifications apportées depuis la dernière sauvegarde (approche incrémentielle).

[WARNING]
====
*Limitation des versions de sauvegarde*

Les sauvegardes de Victoria Metrics remplacent la sauvegarde précédente à chaque fois qu'une nouvelle sauvegarde est exécutée. Cela signifie que vous n'avez accès qu'à la *sauvegarde la plus récente*, et non à un historique de plusieurs versions de sauvegarde.

**Important**: Si une sauvegarde échoue ou si les données sont corrompues, vos données de sauvegarde précédentes peuvent être perdues. Seule la dernière sauvegarde réussie est disponible pour la restauration.

**Exception**: Si le volume de stockage de Victoria Metrics est vidé ou réinitialisé (par exemple, si le répertoire `/storage` est monté vide ou supprimé), le système le détecte et crée automatiquement une nouvelle série de sauvegardes. Dans ce cas, l'ancienne sauvegarde (avant la réinitialisation) et la nouvelle sauvegarde seront préservées et disponibles pour la restauration.
====

[NOTE]
====
*Déploiement de la haute disponibilité*

Les déploiements à haute disponibilité utilisent deux instances de Victoria Metrics (`victoria-metrics-0` et `victoria-metrics-1`). Les sauvegardes sont configurées indépendamment pour chaque instance.
====

=== Calendrier des sauvegardes

Les sauvegardes de Victoria Metrics sont créées toutes les heures :

* `victoria-metrics-0` - 25 minutes après l'heure
* `victoria-metrics-1` - 35 minutes après l'heure

=== Désactiver les sauvegardes programmées

Pour désactiver les sauvegardes planifiées de Victoria Metrics, définissez la planification des sauvegardes pour les deux instances à une date éloignée dans le temps :

[,yaml]
----
victoria-metrics-0:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
victoria-metrics-1:
  backup:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== OpenTelemetry (ClickHouse)

ClickHouse utilise des sauvegardes incrémentielles et complètes. Les anciennes sauvegardes sont supprimées en fonction de la politique de conservation configurée.

=== Calendrier des sauvegardes

Les sauvegardes ClickHouse sont créées :

* Sauvegarde complète - à 00h45 tous les jours
* Sauvegarde incrémentale - 45 minutes après l'heure (de 3h à 12h)

=== Conservation des sauvegardes

Par défaut, l'outil conserve les 308 dernières sauvegardes (complètes et incrémentales), ce qui correspond à ~14 jours.

La rétention des sauvegardes peut être configurée à l'aide de la valeur Helm `clickhouse.backup.config.keep_remote`.

=== Désactiver les sauvegardes programmées

Pour désactiver les sauvegardes ClickHouse planifiées, définissez les planifications des sauvegardes complètes et incrémentielles à une date éloignée dans le temps :

[,yaml]
----
clickhouse:
  backup:
    scheduled:
      full_schedule: '0 0 1 1 1970'         # January 1, 1970 (epoch start)
      incremental_schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----

== Données télémétriques (Elasticsearch)

Les instantanés Elasticsearch sont incrémentiels.

=== Calendrier instantané

Les instantanés Elasticsearch sont créés chaque jour à 03h00, heure du serveur.

=== Conservation des instantanés

Par défaut, les instantanés d'Elasticsearch sont conservés pendant 30 jours, avec un minimum de 5 instantanés et un maximum de 30 instantanés.

La durée de conservation et le nombre d'instantanés conservés peuvent être configurés à l'aide des valeurs Helm suivantes :

* `backup.elasticsearch.scheduled.snapshotRetentionExpireAfter`, spécifiée en https://www.elastic.co/guide/en/elasticsearch/reference/7.6/common-options.html#_time_units[unités de temps Elasticsearch (elastic.co).]
* `backup.elasticsearch.scheduled.snapshotRetentionMinCount`
* `backup.elasticsearch.scheduled.snapshotRetentionMaxCount`

=== Désactiver les instantanés programmés

Pour désactiver les instantanés Elasticsearch programmés, définissez le calendrier des instantanés à une date éloignée dans le temps à l'aide de la valeur Helm `backup.elasticsearch.scheduled.schedule`:

[,yaml]
----
backup:
  elasticsearch:
    scheduled:
      schedule: '0 0 1 1 1970'  # January 1, 1970 (epoch start)
----
